/**
 * Auto-generated i18n key constants
 * Generated from: packages/i18n/locales/en/messages.json
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run `pnpm generate:i18n-keys` to regenerate.
 *
 * Usage:
 * ```typescript
 * import { t } from "@extension/i18n";
 * import { I18N } from "@extension/shared/lib/i18n/keys";
 *
 * // Use with autocomplete and type safety
 * const message = t(I18N.WELCOME);
 * ```
 */

export const I18N = {
  // Extension Metadata
  /**
   * "どこでもメモ"
   *
   * Extension name
   */
  EXTENSION_NAME: 'extensionName' as const,
  /**
   * "直感的なメモのアプリです。"
   *
   * Extension description
   */
  EXTENSION_DESCRIPTION: 'extensionDescription' as const,
  /**
   * "どこでもメモ"
   *
   * The name of the application
   */
  APP_NAME: 'appName' as const,
  /**
   * "どこでもメモ"
   *
   * The short_name (maximum of 12 characters recommended) is a short version of the app's name.
   */
  APP_SHORT_NAME: 'appShortName' as const,
  /**
   * "直感的なメモのアプリです。"
   *
   * The description of the application
   */
  APP_DESCRIPTION: 'appDescription' as const,
  // Misc
  /**
   * "どこでもメモ"
   *
   * The title of the browser action button
   */
  BROWSER_ACTION_TITLE: 'browserActionTitle' as const,
  /**
   * "使い方"
   */
  HOW_TO_USE_PAGE_LINK: 'how_to_use_page_link_msg' as const,
  /**
   * "すべてのメモ"
   */
  SHOW_ALL_NOTE: 'show_all_note_msg' as const,
  /**
   * "検索"
   */
  SEARCH_QUERY: 'search_query_msg' as const,
  /**
   * "このページのメモ一覧"
   */
  THIS_PAGE_NOTE_LIST: 'this_page_note_list_msg' as const,
  /**
   * "どこでもメモについて"
   */
  SETTING_ABOUT_THIS_APP: 'setting_about_this_app' as const,
  /**
   * "制作者"
   */
  SETTING_ABOUT_THIS_APP_CREATED_BY: 'setting_about_this_app_created_by' as const,
  /**
   * "メモ"
   */
  NOTE: 'note' as const,
  /**
   * "更新"
   */
  UPDATED_AT: 'updated_at_msg' as const,
  /**
   * "作成"
   */
  CREATED_AT: 'created_at_msg' as const,
  /**
   * "保存"
   */
  SAVE: 'save_msg' as const,
  /**
   * "キャンセル"
   */
  CANCEL: 'cancel_msg' as const,
  /**
   * "閉じる"
   */
  CLOSE: 'close_msg' as const,
  /**
   * "保存に失敗しました。"
   */
  SAVE_ERROR: 'save_error_msg' as const,
  /**
   * "再度お試しください。"
   */
  SAVE_ERROR_MSG_2: 'save_error_msg_2' as const,
  /**
   * "文字数を減らして、再度お試しください。"
   */
  SAVE_ERROR_WORD_MAXIMUM: 'save_error_word_maximum_msg' as const,
  /**
   * "変更を破棄して閉じる"
   */
  DISCARD_CLOSE: 'discard_close_msg' as const,
  /**
   * "このページに移動する"
   */
  GO_TO_THIS_PAGE: 'go_to_this_page' as const,
  /**
   * "メモを入力"
   */
  INPUT_DESCRIPTION_PLACEHOLDER: 'input_description_placeholder' as const,
  /**
   * "クリップボードにコピーする"
   */
  DO_COPY: 'do_copy_msg' as const,
  /**
   * "コピーしました"
   */
  COPIED: 'copied_msg' as const,
  /**
   * "あり"
   */
  PIN_SELECT_OPTION_UNFIXED: 'pin_select_option_unfixed_msg' as const,
  /**
   * "なし"
   */
  PIN_SELECT_OPTION_FIXED: 'pin_select_option_fixed_msg' as const,
  /**
   * "縮小する"
   */
  OPEN_SELECT_OPTION_YES: 'open_select_option_yes_msg' as const,
  /**
   * "縮小しない"
   */
  OPEN_SELECT_OPTION_NO: 'open_select_option_no_msg' as const,
  /**
   * "高さ"
   */
  SIZE_HEIGHT: 'size_height_msg' as const,
  /**
   * "幅"
   */
  SIZE_WIDTH: 'size_width_msg' as const,
  /**
   * "位置をリセット"
   */
  RESET_POSITION: 'reset_position_msg' as const,
  /**
   * "ピンを切り替える"
   */
  SWITCH_PIN: 'switch_pin_msg' as const,
  /**
   * "最小化する"
   */
  MINIMIZE: 'minimize_msg' as const,
  /**
   * "最大化"
   */
  MAXIMIZE: 'maximize_msg' as const,
  /**
   * "画面に固定する"
   */
  PINNED: 'pinned_msg' as const,
  /**
   * "ページに固定する"
   */
  REMOVE_PINNED: 'remove_pinned_msg' as const,
  /**
   * "コピー"
   */
  COPY: 'copy_msg' as const,
  /**
   * "書き出し"
   */
  EXPORT: 'export_msg' as const,
  /**
   * "CSVダウンロード"
   */
  CSV_DOWNLOAD: 'csv_download_msg' as const,
  /**
   * "txtダウンロード"
   */
  TEXT_DOWNLOAD: 'text_download_msg' as const,
  /**
   * "ページをリロードしてください。"
   */
  PLEASE_RELOAD: 'please_reload_msg' as const,
  /**
   * "製作者"
   */
  MAKER: 'maker_msg' as const,
  /**
   * "メモの初期カラー"
   */
  DEFAULT_COLOR: 'default_color_msg' as const,
  /**
   * "新しく作成するメモのデフォルトカラーを設定できます。"
   */
  DEFAULT_COLOR_DESCRIPTION: 'default_color_description' as const,
  /**
   * "新しいメモ"
   */
  NEW_NOTE_TITLE: 'new_note_title_msg' as const,
  /**
   * "ページの読み込みに失敗しました。"
   */
  FAILED_LOAD_PAGE: 'failed_load_page_msg' as const,
  /**
   * "リンクが正しくないと、正常にメモが表示されない場合があります。"
   */
  LINK_EDIT_NOTE: 'link_edit_note_msg' as const,
  /**
   * "ダブルクリックで編集"
   */
  NEW_NOTE_DESCRIPTION: 'new_note_description_msg' as const,
  // Messages
  /**
   * "ようこそ、どこでもメモへ！"
   */
  WELCOME: 'welcome_msg' as const,
  /**
   * "メモがありません。"
   */
  NO_NOTE: 'no_note_msg' as const,
  /**
   * "メモを追加する"
   */
  ADD_NOTE: 'add_note_msg' as const,
  /**
   * "削除してよろしいですか？"
   */
  CONFIRM_REMOVE_NOTE: 'confirm_remove_note_msg' as const,
  /**
   * "を削除してよろしいですか？"
   */
  CONFIRM_REMOVE_NEXT_NOTE: 'confirm_remove_next_note_msg' as const,
  /**
   * "このページではメモを表示できません。"
   */
  CANNOT_SHOW_NOTE: 'cannot_show_note_msg' as const,
  /**
   * "メモを作成する。"
   */
  NO_NOTE_CREATED: 'no_note_created_msg' as const,
  /**
   * "もしくは、右クリック「メモを追加する」から作成できます。"
   */
  NO_NOTE_CREATED_OPTION: 'no_note_created_option_msg' as const,
  /**
   * "この画面ではメモの作成はできません"
   */
  NOTE_UNAVAILABLE: 'note_unavailable_msg' as const,
  // Buttons
  /**
   * "メモを作成する"
   */
  MAKE_NOTE_BUTTON: 'make_note_button_msg' as const,
  /**
   * "設定"
   */
  SETTING_BUTTON: 'setting_button_msg' as const,
  /**
   * "メモ一覧ページ"
   */
  MENU_BUTTON: 'menu_button_msg' as const,
  // Headers
  /**
   * "メモ一覧"
   */
  NOTE_HEADER: 'note_header_msg' as const,
  /**
   * "設定"
   */
  SETTINGS_HEADER: 'settings_header_msg' as const,
  /**
   * "使い方"
   */
  HOW_TO_USE_HEADER: 'how_to_use_header_msg' as const,
  // Usage Instructions
  /**
   * "ポップアップを固定することをおすすめします。"
   */
  USAGE01: 'usage01' as const,
  /**
   * "ポップアップを開き、「+」ボタンをクリックしてメモを作成できます。"
   */
  USAGE02: 'usage02' as const,
  /**
   * "もしくは画面上で右クリックのメニューから作成できます。"
   */
  USAGE02_2: 'usage02_2' as const,
  /**
   * "ダブルクリックでタイトルと詳細を編集できます。"
   */
  USAGE03: 'usage03' as const,
  /**
   * "マウスドラッグで移動可能です。リサイズをすることもできます。"
   */
  USAGE04: 'usage04' as const,
  /**
   * "ポップアップから、今開いているページで作成したメモを閲覧することができます。"
   */
  USAGE05: 'usage05' as const,
  /**
   * "メモ一覧ページ"
   */
  USAGE06: 'usage06' as const,
  /**
   * "で今まで作ったメモを一覧できます。"
   */
  USAGE06_2: 'usage06_2' as const,
  /**
   * "メモには、様々な機能があります。"
   */
  USAGE07: 'usage07' as const,
  // Sort Options
  /**
   * "更新日"
   */
  UPDATED_AT_SORT_OPTION: 'updated_at_sort_option' as const,
  /**
   * "作成日"
   */
  CREATED_AT_SORT_OPTION: 'created_at_sort_option' as const,
  /**
   * "タイトル"
   */
  TITLE_SORT_OPTION: 'title_sort_option' as const,
  // Labels
  /**
   * "ピン"
   */
  PIN: 'pin_msg' as const,
  /**
   * "カラー"
   */
  COLOR: 'color_msg' as const,
  /**
   * "縮小"
   */
  OPEN: 'open_msg' as const,
  /**
   * "サイズ"
   */
  SIZE: 'size_msg' as const,
  /**
   * "位置"
   */
  POSITION: 'position_msg' as const,
  /**
   * "詳細"
   */
  DETAIL: 'detail_msg' as const,
  /**
   * "編集"
   */
  EDIT: 'edit_msg' as const,
  /**
   * "削除する"
   */
  DELETE: 'delete_msg' as const,
  // Explanations
  /**
   * "メモをピン留めすると、スクロールに追従します。"
   */
  PIN_EXPLAIN: 'pin_explain_msg' as const,
  /**
   * "メモを編集モードに切り替えます。（もしくはダブルクリックで編集できます）"
   */
  EDIT_EXPLAIN: 'edit_explain_msg' as const,
  /**
   * "メモのテキストをクリップボードにコピーします。"
   */
  COPY_EXPLAIN: 'copy_explain_msg' as const,
  /**
   * "メモのカラーを編集します。"
   */
  COLOR_EXPLAIN: 'color_explain_msg' as const,
  /**
   * "メモを削除します。"
   */
  DELETE_EXPLAIN: 'delete_explain_msg' as const,
  /**
   * "メモを最小化します。"
   */
  OPEN_EXPLAIN: 'open_explain_msg' as const,
  // Error Display
  /**
   * "エラーが発生しました"
   */
  DISPLAY_ERROR_INFO: 'displayErrorInfo' as const,
  /**
   * "申し訳ございません。ページの読み込み中に問題が発生しました。"
   */
  DISPLAY_ERROR_DESCRIPTION: 'displayErrorDescription' as const,
  /**
   * "エラーの詳細:"
   */
  DISPLAY_ERROR_DETAILS_INFO: 'displayErrorDetailsInfo' as const,
  /**
   * "不明なエラー"
   */
  DISPLAY_ERROR_UNKNOWN_ERROR_INFO: 'displayErrorUnknownErrorInfo' as const,
  /**
   * "再実行"
   */
  DISPLAY_ERROR_RESET: 'displayErrorReset' as const,
} as const;

/**
 * Union type of all valid i18n keys
 */
export type I18nKey = (typeof I18N)[keyof typeof I18N];
